config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :trailers
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'home/contact'

  # Defines the root path route ("/")
   root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/trailer.rb
class Trailer < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :trailers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def contact
  end
end

app/controllers/trailers_controller.rb
class TrailersController < ApplicationController
  before_action :set_trailer, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, exept: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /trailers or /trailers.json
  def index
    @trailers = Trailer.all
  end

  # GET /trailers/1 or /trailers/1.json
  def show
  end

  # GET /trailers/new
  def new
    @trailer = Trailer.new
    #@trailer = current_user.trailer.build
  end

  # GET /trailers/1/edit
  def edit
  end

  # POST /trailers or /trailers.json
  def create
    @trailer = Trailer.new(trailer_params)
    #@trailer = current_user.trailer.build(trailer_params)
    respond_to do |format|
      if @trailer.save
        format.html { redirect_to trailer_url(@trailer), notice: "Trailer was successfully created." }
        format.json { render :show, status: :created, location: @trailer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @trailer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trailers/1 or /trailers/1.json
  def update
    respond_to do |format|
      if @trailer.update(trailer_params)
        format.html { redirect_to trailer_url(@trailer), notice: "Trailer was successfully updated." }
        format.json { render :show, status: :ok, location: @trailer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @trailer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trailers/1 or /trailers/1.json
  def destroy
    @trailer.destroy

    respond_to do |format|
      format.html { redirect_to trailers_url, notice: "Trailer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    #@trailer = current_user.trailer.find_by(id: params[:id])
    @trailer = Trailer.find_by(id: params[:id])
    redirect_to trailer_path, notice: "Not Authorized to Edit" if @trailer.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trailer
      @trailer = Trailer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def trailer_params
      params.require(:trailer).permit(:trailer_number, :order_number, :trucking_company, :truck_number, :trailer_location, :dock_number, :live_load, :timer, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/trailers_helper.rb
module TrailersHelper
end

app/views/home/_footer.html.erb
<footer class="footer bg-dark text-center text-lg-start fixed-bottom">
  <!-- Grid container -->
  <div class="container p-4">
    <!--Grid row-->
    <div class="row">
      <!--Grid column-->
      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">

        <ul class="list-unstyled mb-0">
          <li>
            <a href="https://www.admiralbeverage.com/" class="text-white">Admiral Beverage</a>
          </li>
          <li>
            <a href="https://www.pepsi.com/" class="text-white">Pepsi</a>
          </li>
          <li>
            <a href="https://www.mountaindew.com/" class="text-white">Mountain Dew</a>
          </li>
          <li>
            <a href="https://www.keurigdrpepper.com/" class="text-white">Keurig</a>
          </li>
        </ul>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">

        <ul class="list-unstyled">
          <li>
            <a href="https://www.drpepper.com/s/" class="text-white">Dr Pepper</a>
          </li>
          <li>
            <a href="https://www.aquavistawater.com/" class="text-white">Aquavista</a>
          </li>
          <li>
            <a href="https://www.aquafina.com/en-US/" class="text-white">Aquafina</a>
          </li>
          <li>
            <a href="https://polarseltzer.com/" class="text-white">Polar</a>
          </li>
        </ul>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">

        <ul class="list-unstyled mb-0">
          <li>
            <a href="https://www.bubly.com/#/" class="text-white">Bubly</a>
          </li>
          <li>
            <a href="https://www.7up.com/en" class="text-white">7Up</a>
          </li>
          <li>
            <a href="https://www.rootbeer.com/" class="text-white">A & W</a>
          </li>
          <li>
            <a href="https://www.canadadry.com/" class="text-white">Canada Dry</a>
          </li>
        </ul>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">

        <ul class="list-unstyled">
          <li>
            <a href="https://www.crushsoda.com/" class="text-white">Crush</a>
          </li>
          <li>
            <a href="https://www.squirtsoda.com/" class="text-white">Squirt</a>
          </li>
          <li>
            <a href="https://www.sunkistsoda.com/" class="text-white">Sunkist</a>
          </li>
          <li>
            <a href="https://findyournorthwest.com/clients/merchants-craft/" class="text-white">Merchant's Craft</a>
          </li>
        </ul>
      </div>
      <!--Grid column-->
    </div>
    <!--Grid row-->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3 text-white" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2023 Copyright design by Cade Hansen
  </div>
</footer>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <!-- < link_to "Trailer App", trailers_path, class:"navbar-brand" %> -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact Us", home_contact_path, class:"nav-link" %>
        </li>
        

      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to "View All Trailers", trailers_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Add Trailer", new_trailer_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign Out", destroy_user_session_path, data: { "turbo-method": :delete }, class:"nav-link active" %>
      </li>

   <% else %>
      <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign In", new_user_session_path, class:"nav-link active" %>
      </li>
    <% end %>
    </ul> 
    </div>
  </div>
</nav>

app/views/home/contact.html.erb
<h1>Contact Us</h1><br>
<p>
	<strong>ADDRESS:</strong><br>
	<a href="https://www.google.com/maps/place/Admiral+Beverage/@43.6119446,-116.5701358,17z/data=!4m15!1m8!3m7!1s0x54ae4cdd07fd5b63:0x4ab5a0f7023cee7f!2s8925+Birch+Ln,+Nampa,+ID+83687!3b1!8m2!3d43.6119446!4d-116.5701358!16s%2Fg%2F11c1hpk2qm!3m5!1s0x54ae4da39aeac3c1:0xfa7cc37a981a9de5!8m2!3d43.6098594!4d-116.5705413!16s%2Fg%2F11gjxkrkh9?entry=ttu">8925 Birch Ln<br>
	Nampa, ID 83687<br></a>
	<br>
	<strong>PHONE:</strong><br>
	<a href="tel:+2084669310">(208) 466-9310</a><br>
	<br>
	<strong>WEBSITE:</strong><br>
	<a href="https://www.admiralbeverage.com/">admiralbeverage.com</a>
</p>

app/views/home/index.html.erb
<h1 class="text-center">WELCOME</h1>
<h2 class="text-center">to Admiral's Trailer App</h2>
<br><br>
<div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag("Admiral-Logo.jpg", :alt => "Admiral Beverage Logo", class: "d-block mx-auto") %>
    </div>
    <div class="carousel-item">
      <%= image_tag("pepsi-new-logo-2023.jpg", :alt => "Pepsi Logo", class: "d-block mx-auto") %>
    </div>
    <div class="carousel-item">
      <%= image_tag("Mountain_Dew_logo.png", :alt => "Mt Dew Logo", class: "d-block mx-auto") %>
    </div>
    <div class="carousel-item">
      <%= image_tag("KDP_new_logo.jpg", :alt => "Keurig Logo", class: "d-block mx-auto") %>
    </div>
    <div class="carousel-item">
      <%= image_tag("Dr-Pepper-Logo.png", :alt => "Dr Pepper Logo", class: "d-block mx-auto") %>
    </div>
    <div class="carousel-item">
      <%= image_tag("better_aquavist_logo.jpg", :alt => "Aquavista Logo", class: "d-block mx-auto") %>
    </div>
    <div class="carousel-item">
      <%= image_tag("Aquafina-Logo-2004.jpg", :alt => "Aquafina Logo", class: "d-block mx-auto") %>
    </div>
    <div class="carousel-item">
      <%= image_tag("Polar_logo.png", :alt => "Polar Logo", class: "d-block mx-auto") %>
    </div>
    <div class="carousel-item">
      <%= image_tag("bubly_0.jpg", :alt => "Bubly Logo", class: "d-block mx-auto") %>
    </div>
    <div class="carousel-item">
      <%= image_tag("7Up-Logo.png", :alt => "7Up Logo", class: "d-block mx-auto") %>
    </div>
    <div class="carousel-item">
      <%= image_tag("AW_Root_Beer_logo.png", :alt => "A&W Root Beer Logo", class: "d-block mx-auto") %>
    </div>
    <div class="carousel-item">
      <%= image_tag("Canada-Dry-Logo.png", :alt => "Canada Dry Logo", class: "d-block mx-auto") %>
    </div>
    <div class="carousel-item">
      <%= image_tag("Crush-Logo.jpg", :alt => "Crush Logo", class: "d-block mx-auto") %>
    </div>
    <div class="carousel-item">
      <%= image_tag("Squirt_Logo.png", :alt => "Squirt Logo", class: "d-block mx-auto") %>
    </div>
    <div class="carousel-item">
      <%= image_tag("sunkist_logo.jpg", :alt => "Sunkist Logo", class: "d-block mx-auto") %>
    </div>
    <div class="carousel-item">
      <%= image_tag("MerchantsCraftLogo1.jpg", :alt => "Merchants Craft Logo", class: "d-block mx-auto") %>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
  </button>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Trailers</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "turbo", type: "module" %>
  </head>

  <body>
    
    <%= render 'home/header' %>
    

    <div class= container>
      <br>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      
      <%= yield %>
    </div>

    <%= render 'home/footer' %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

app/views/trailers/_form.html.erb
<%= form_with(model: trailer) do |form| %>
  <% if trailer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(trailer.errors.count, "error") %> prohibited this trailer from being saved:</h2>

      <ul>
        <% trailer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class = "field form-group">
    <% form.label :trailer_number, style: "display: block" %>
    <%= form.number_field :trailer_number, class: "form-control", placeholder: "Trailer Number" %>
  </div>
<br>
  <div class = "field form-group">
    <% form.label :order_number, style: "display: block" %>
    <%= form.number_field :order_number, class: "form-control", placeholder: "Order Number" %>
  </div>
<br>
  <div class = "field form-group">
    <% form.label :trucking_company, style: "display: block" %>
    <%= form.text_field :trucking_company, class: "form-control", placeholder: "Trucking Company" %>
  </div>
<br>
  <div class = "field form-group">
    <% form.label :truck_number, style: "display: block" %>
    <%= form.number_field :truck_number, class: "form-control", placeholder: "Truck Number" %>
  </div>
<br>
  <div class = "field form-group">
    <% form.label :trailer_location, style: "display: block" %>
    <%= form.text_field :trailer_location, class: "form-control", placeholder: "Trailer Location" %>
  </div>
<br>
  <div class = "field form-group">
    <% form.label :dock_number, style: "display: block" %>
    <%= form.number_field :dock_number, class: "form-control", placeholder: "Dock Number" %>
  </div>
<br>
  <div class = "field form-group">
    <% form.label :live_load, style: "display: block" %>
    <%= form.text_field :live_load, class: "form-control", placeholder: "Live Load" %>
  </div>
<br>
  <div class = "field form-group">
    <% form.label :timer, style: "display: block" %>
    <%= form.datetime_field :timer, class: "form-control", placeholder: "Start Time in Dock" %>
  </div>
  <br>
    <div class = "field form-group">
    <% form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id, id: :trailer_user_id, class: "form-control", value: current_user.id, type: :hidden %>
  </div>
  <% current_user.id %>
<br>
  <div class="actions">
    <%= form.submit class:'btn btn-primary'%>
  </div>
<% end %>

app/views/trailers/_trailer.html.erb
<figure>
  <%= image_tag("truckAndTrailer2.png", :alt => "Truck and Trailer",  style: 'height:10%; width:auto;') %>
  <figcaption>Trailer #: <%= link_to trailer do %>
  <%= trailer.trailer_number%>
<% end %></figcaption>
</figure>


<% trailer.trailer_number %>

app/views/trailers/edit.html.erb
<h1>Editing trailer</h1>
<br>
<%= render "form", trailer: @trailer %>

<br>

<div>
  <%= link_to "Show this trailer", @trailer, class: "btn btn-dark" %> |
  <%= link_to "Back to trailers", trailers_path, class: "btn btn-dark" %> |
  <%= link_to "Delete this trailer", @trailer,  data: { "turbo-method": :delete, turbo_confirm: 'Are you sure you want to delete trailer?' }, class: "btn btn-danger" %>
</div>

app/views/trailers/index.html.erb
<h1>Trailers</h1>
<br>
<div id="trailers">
  <% @trailers.each do |trailer| %>
  <!-- < if trailer.user == current_user %> -->
    <%= render trailer %>
    <br>
    <p>
      <% link_to "Show this trailer", trailer, class:"btn btn-dark" %>
    </p>
  <% end %>
  <!-- < end %> -->
</div>

<%= link_to "Add New Trailer", new_trailer_path, class:"btn btn-outline-dark btn-lg" %>

app/views/trailers/new.html.erb
<h1>New trailer</h1>

<%= render "form", trailer: @trailer %>

<br>

<div>
  <%= link_to "Back to trailers", trailers_path, class: "btn btn-dark" %>
</div>

app/views/trailers/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= @trailer.trailer_number %></h1>
  <p class="lead">
      Order Number:
      <%= @trailer.order_number %><br>
      Trucking Company: 
      <%= @trailer.trucking_company %><br>
      Truck Number: 
      <%= @trailer.truck_number %><br>
      Trailer Location: 
      <%= @trailer.trailer_location %><br>
      Dock Number: 
      <%= @trailer.dock_number %><br>
      Live Load: 
      <%= @trailer.live_load %><br>
      Start time in Dock: 
      <%= @trailer.timer %>
      <% render @trailer %>
  </p>
  <%= link_to "Edit this trailer", edit_trailer_path(@trailer), class: "btn btn-warning" %> |
  <%= link_to "Back to trailers", trailers_path, class: "btn btn-dark" %> |
  <%= link_to "Delete this trailer", @trailer,  data: { "turbo-method": :delete, turbo_confirm: 'Are you sure you want to delete trailer?' }, class: "btn btn-danger" %>
</div>